baseURL = "https://kshannon.github.io/cogs9/"
languageCode = "en-us"
title = "Cogs9: Intro To Data Science"
publishDir = "docs"

[params]
  courseName = "Cogs 9: Introduction To Data Science"
  courseDate = "UCSD - 2022 Summer Session II"

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 5
    ordered = false